# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0zM0ltpfuBUzc-cFpdoLDpFRw_VZ9G_

# **Codveda Tasks:  Level 1**
##Task 1: Stock Prices Dataset - Data Cleaning & Preprocessing

## **Project Overview**

This project demonstrates the process of cleaning and preprocessing a stock prices dataset using Python and Pandas. The objective is to improve data quality by identifying and handling missing values, removing duplicate records, correcting data types, and standardizing data formats. These preprocessing steps ensure that the dataset is accurate, consistent, and ready for further analysis or predictive modeling.

## Dataset Description

This dataset contains daily stock market information for multiple companies. Each row represents the trading activity of one company's stock on a specific date.

### Features

| Column | Description |
|---------|-------------|
| symbol | Stock ticker symbol (e.g., AAPL, MSFT) |
| date | Trading date |
| open | Opening stock price |
| high | Highest stock price during the trading day |
| low | Lowest stock price during the trading day |
| close | Closing stock price |
| volume | Number of shares traded during the day |

***Import Dataset***
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Stock Prices Data Set.csv')

"""##Initial Data Inspection

This section shows the state of the raw data before cleaning.
"""

print("Dataset Shape:", df.shape)
df.head()

"""***Identifying Missing Values***"""

missing_rows = df[df.isnull().any(axis=1)]
print(missing_rows)

df['date'] = pd.to_datetime(df['date'])
print(df.info())

"""***Handling Missing Values***  
Replacing missing prices with the industry standard method that is **Forward-Fill** grouped by stock symbol, which carries forward the stock's previous trading day's price
"""

df['open']=df.groupby('symbol')['open'].ffill()
df['high']=df.groupby('symbol')['high'].ffill()
df['low']=df.groupby('symbol')['low'].ffill()

df['open']=df.groupby('symbol')['open'].bfill()
df['high']=df.groupby('symbol')['high'].bfill()
df['low']=df.groupby('symbol')['low'].bfill()

"""### Checking & Removing Duplicate Rows
 Removing duplicates helps avoid biased analyses and inaccurate results.
"""

print(f"Duplicates: {df.duplicated().sum()}")

"""***Standardizing Inconsistent Data Formats***


1.  Convert date format from string to datetime object
2.  Stripping symbols from accidental leading or trailing space and convert it to uppercase
3.  Ensure price and volume columns are numeric  
"""

df.info()

numeric_cols=['open','high','low','close','volume']
df[numeric_cols]=df[numeric_cols].apply(pd.to_numeric)

df = df.sort_values(by=['symbol','date']).reset_index(drop=True)

print("Missing values after cleaning:\n",df.isnull().sum())
print("\n Clean Data Types: \n", df.dtypes)
df.info()

"""The dataset was standardized to ensure consistency across all records. The **date** column was converted to the appropriate `datetime` format for accurate time-based analysis, stock ticker symbols were standardized by converting them to uppercase, and the data types of all columns were verified to ensure they were stored in formats suitable for analysis.

# Conclusion

The stock prices dataset was successfully cleaned and preprocessed using Python and Pandas. Data quality issues, including missing values, duplicate records, inconsistent date formats, and categorical formatting, were addressed. The resulting dataset is now accurate, consistent, and ready for further analysis or machine learning applications.
"""